#!/usr/bin/env python

# this generator requires https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/rabbitmq_codegen to work
import re

from rabbitmq_codegen.amqp_codegen import *

# utilities


def constant_name(c):
    return "".join([p.capitalize() for p in re.split("[- ]", c)])


SPEC_TYPE_TO_SWIFT = {
    "octet": "Int8",
    "shortstr": "String",
    "longstr": "String",
    "short": "Int16",
    "long": "Int32",
    "longlong": "Int64",
    "bit": "Bool",
    "table": "[String: FieldValue]",
    "timestamp": "Date",
}


def as_camel_case(startUpper, name):
    camel_cased = "".join(c for c in name.title() if c.isalnum())
    if not startUpper:
        return camel_cased[0].lower() + camel_cased[1:]
    return camel_cased


def struct_name(name):
    return as_camel_case(True, name)


def variable_name(name):
    if name == "internal":
        return "`internal`"
    return as_camel_case(False, name)


def swift_type(spec, domain):
    return SPEC_TYPE_TO_SWIFT[spec.resolveDomain(domain)]


# ---------------------------------------------------------------------------


def print_file_header():
    print(
        """//   NOTE: This -*- swift -*- source code is autogenerated from the AMQP
//         specification!
//
// TODO: license here
//
"""
    )


def gen_swift_api_from_spec(spec: AmqpSpec):
    def protocols():
        print(
            """protocol AMQPObjectProtocol: Equatable {
    var amqpName: String { get }
}

protocol AMQPClassProtocol: AMQPObjectProtocol {
    var amqpClassId: UInt16 { get }
}

protocol AMQPPropertiesProtocol: AMQPObjectProtocol, Hashable { }

protocol AMQPMethodProtocol: AMQPClassProtocol {
    var amqpMethodId: UInt16 { get }
}"""
        )

    def FieldValueEnum():
        print("    public enum FieldValue: Equatable, Hashable {")
        print("        case long(Int32),")
        print("        decimal(UInt8, Int32),")
        print("        longstr(String),")
        print("        timestamp(Date),")
        print("        table([String: FieldValue]),")
        print("        void")
        print("")
        print("        var type: UInt8 {")
        print("            switch self {")
        print('            case .long: return Character("I").asciiValue!')
        print('            case .decimal: return Character("D").asciiValue!')
        print('            case .longstr: return Character("S").asciiValue!')
        print('            case .timestamp: return Character("T").asciiValue!')
        print('            case .table: return Character("F").asciiValue!')
        print('            case .void: return Character("V").asciiValue!')
        print("            }")
        print("        }")
        print("    }")

    def header():
        print_file_header()
        print("import Foundation")

    def amqp_constants():
        print()
        print("    public struct ProtocolLevel {")
        print(f"        static let MAJOR = {spec.major}")
        print(f"        static let MINOR = {spec.minor}")
        print(f"        static let REVISION = {spec.revision}")
        print(f"        static let PORT = {spec.port}")
        print("    }")
        print()
        for c, v, _ in spec.constants:
            print(f"    static let {constant_name(c)} = {v}")

    def amqp_classes_and_methods():
        for c in spec.classes:
            print()
            print(f"    public struct {struct_name(c.name)} : AMQPClassProtocol {{")
            print(f"        public var amqpClassId: UInt16 {{ {c.index} }}")
            print(f'        public var amqpName: String {{ "{c.name}" }}')
            for m in c.allMethods():
                print()
                print(f"        public struct {struct_name(m.name)} : AMQPMethodProtocol {{")
                for a in m.arguments:
                    print(f"           private(set) var {variable_name(a.name)}: {swift_type(spec, a.domain)}")
                print()
                print(f"           public var amqpClassId: UInt16 {{ {c.index} }}")
                print(f"           public var amqpMethodId: UInt16 {{ {m.index} }}")
                print(f'           public var amqpName: String {{ "{c.name}.{m.name}" }}')
                print("        }")
            print("    }")

    def specific_properties(c):
        structName = struct_name(c.name)

        print()
        print(f"    public struct {structName}Properties : AMQPPropertiesProtocol {{")
        for f in c.fields:
            print(f"        private(set) var {variable_name(f.name)}: {swift_type(spec, f.domain)}")

        print()
        print(f"        public var amqpClassId: UInt16 {{ {c.index} }}")
        print(f'        public var amqpName: String {{ "{c.name}" }}')
        print("    }")

    def amqp_properties_classes():
        for c in spec.classes:
            if c.hasContentProperties:
                specific_properties(c)

    def amqp_spec():
        print("public struct AMQP {")

        FieldValueEnum()
        amqp_constants()
        amqp_classes_and_methods()
        amqp_properties_classes()

        print("}")

    header()
    print()
    protocols()
    print()
    amqp_spec()


# --------------------------------------------------------------------------------


def gen_swift_api(specPath):
    gen_swift_api_from_spec(AmqpSpec(specPath))


def gen_swift_impl(specPath):
    pass


if __name__ == "__main__":
    do_main(gen_swift_api, gen_swift_impl)
