disabled_rules:
  # well, I just can't help myself
  - file_length
  # eventually I will use issue management software
  - todo
  - nesting
  # rely on swift format for the next ones
  - trailing_comma
  - opening_brace

type_name:
  excluded:
    - Tx # forced by Spec
