SPEC_TYPE_TO_SWIFT = {
    "octet": "Int8",
    "shortstr": "String",
    "longstr": "String",
    "short": "Int16",
    "long": "Int32",
    "longlong": "Int64",
    "bit": "Bool",
    "table": "[String: FieldValue]",
    "timestamp": "Date",
}


def constant_name(c):
    return "".join([p.capitalize() for p in re.split("[- ]", c)])


def as_camel_case(startUpper: bool, name: str):
    camel_cased = "".join(c for c in name.title() if c.isalnum())
    if not startUpper:
        return camel_cased[0].lower() + camel_cased[1:]
    return camel_cased


def struct_name(name: str):
    return as_camel_case(True, name)


def variable_name(name: str, escapingInternal: bool = True):
    if escapingInternal and name == "internal":
        return "`internal`"
    return as_camel_case(False, name)


def swift_type(spec, domain):
    return SPEC_TYPE_TO_SWIFT[spec.resolveDomain(domain)]


def default_value(spec, domain: str, value) -> str:
    t = swift_type(spec, domain)
    if t == "String":
        return f'"{value}"'
    if domain == "table" and (value == "{}" or value == {}):
        return "[:]"
    if domain in ["octet", "short", "long", "longlong"]:
        return value
    if t == "Bool":
        return str(value).lower()
    # if t == "timestamp":
    raise RuntimeError(f"Unknown domain - type - value: {domain} - {t} - {value}")


def get_bytes_count(spec, arg_name: str, domain: str):

    t = swift_type(spec, domain)
    domain = spec.resolveDomain(domain)
    if domain == "shortstr":
        return f"UInt32({variable_name(arg_name, False)}.shortBytesCount)"
    if domain == "longstr":
        return f"{variable_name(arg_name, False)}.longBytesCount"
    if domain == "table":
        return f"{variable_name(arg_name, False)}.bytesCount"
    if t.startswith("Int"):
        return f"{int(t.lstrip('Int')) // 8}"
    if t == "Bool":
        return "1"
    if t == "Date":
        return "8"
    raise RuntimeError(f"Unknown domain - type: {domain} - {t}")


def print_file_header():
    print(
        """//   NOTE: This -*- swift -*- source code is autogenerated from the AMQP
//         specification!
//
// TODO: license here
//
"""
    )


def as_bool_literal(val: bool):
    return "true" if val else "false"
