//   NOTE: This -*- swift -*- source code is autogenerated from the AMQP
//         specification!
//
// This source file is part of the swift-amqp open source project
//
// Copyright (c) 2024-2025 swift-amqp project authors
// Licensed under Apache License 2.0
//
// See LICENSE for license information
//
// SPDX-License-Identifier: Apache-2.0
//

import Testing

@testable import AMQP

@Suite struct BasicCoding {
    @Test("Spec.Basic.Qos default encoding/decoding roundtrip")
    func amqpBasicQosCoding() async throws {
        let object = Spec.Basic.Qos()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.Qos.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.QosOk default encoding/decoding roundtrip")
    func amqpBasicQosOkCoding() async throws {
        let object = Spec.Basic.QosOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.QosOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.Consume default encoding/decoding roundtrip")
    func amqpBasicConsumeCoding() async throws {
        let object = Spec.Basic.Consume()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.Consume.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.ConsumeOk default encoding/decoding roundtrip")
    func amqpBasicConsumeOkCoding() async throws {
        let object = Spec.Basic.ConsumeOk(consumerTag: "FooBar")
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.ConsumeOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.Cancel default encoding/decoding roundtrip")
    func amqpBasicCancelCoding() async throws {
        let object = Spec.Basic.Cancel(consumerTag: "FooBar")
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.Cancel.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.CancelOk default encoding/decoding roundtrip")
    func amqpBasicCancelOkCoding() async throws {
        let object = Spec.Basic.CancelOk(consumerTag: "FooBar")
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.CancelOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.Publish default encoding/decoding roundtrip")
    func amqpBasicPublishCoding() async throws {
        let object = Spec.Basic.Publish()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.Publish.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.Return default encoding/decoding roundtrip")
    func amqpBasicReturnCoding() async throws {
        let object = Spec.Basic.Return(replyCode: 1, exchange: "FooBar", routingKey: "FooBar")
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.Return.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.Deliver default encoding/decoding roundtrip")
    func amqpBasicDeliverCoding() async throws {
        let object = Spec.Basic.Deliver(
            consumerTag: "FooBar",
            deliveryTag: 1,
            exchange: "FooBar",
            routingKey: "FooBar"
        )
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.Deliver.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.Get default encoding/decoding roundtrip")
    func amqpBasicGetCoding() async throws {
        let object = Spec.Basic.Get()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.Get.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.GetOk default encoding/decoding roundtrip")
    func amqpBasicGetOkCoding() async throws {
        let object = Spec.Basic.GetOk(
            deliveryTag: 1,
            exchange: "FooBar",
            routingKey: "FooBar",
            messageCount: 1
        )
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.GetOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.GetEmpty default encoding/decoding roundtrip")
    func amqpBasicGetEmptyCoding() async throws {
        let object = Spec.Basic.GetEmpty()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.GetEmpty.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.Ack default encoding/decoding roundtrip")
    func amqpBasicAckCoding() async throws {
        let object = Spec.Basic.Ack()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.Ack.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.Reject default encoding/decoding roundtrip")
    func amqpBasicRejectCoding() async throws {
        let object = Spec.Basic.Reject(deliveryTag: 1)
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.Reject.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.RecoverAsync default encoding/decoding roundtrip")
    func amqpBasicRecoverAsyncCoding() async throws {
        let object = Spec.Basic.RecoverAsync()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.RecoverAsync.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.Recover default encoding/decoding roundtrip")
    func amqpBasicRecoverCoding() async throws {
        let object = Spec.Basic.Recover()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.Recover.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.RecoverOk default encoding/decoding roundtrip")
    func amqpBasicRecoverOkCoding() async throws {
        let object = Spec.Basic.RecoverOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.RecoverOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Basic.Nack default encoding/decoding roundtrip")
    func amqpBasicNackCoding() async throws {
        let object = Spec.Basic.Nack()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Basic.Nack.self, from: binary)
        #expect(decoded == object)
    }

}

@Suite struct ConnectionCoding {
    @Test("Spec.Connection.Start default encoding/decoding roundtrip")
    func amqpConnectionStartCoding() async throws {
        let object = Spec.Connection.Start(serverProperties: .init())
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Connection.Start.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Connection.StartOk default encoding/decoding roundtrip")
    func amqpConnectionStartOkCoding() async throws {
        let object = Spec.Connection.StartOk(clientProperties: .init(), response: "FooBar")
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Connection.StartOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Connection.Secure default encoding/decoding roundtrip")
    func amqpConnectionSecureCoding() async throws {
        let object = Spec.Connection.Secure(challenge: "FooBar")
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Connection.Secure.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Connection.SecureOk default encoding/decoding roundtrip")
    func amqpConnectionSecureOkCoding() async throws {
        let object = Spec.Connection.SecureOk(response: "FooBar")
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Connection.SecureOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Connection.Tune default encoding/decoding roundtrip")
    func amqpConnectionTuneCoding() async throws {
        let object = Spec.Connection.Tune()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Connection.Tune.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Connection.TuneOk default encoding/decoding roundtrip")
    func amqpConnectionTuneOkCoding() async throws {
        let object = Spec.Connection.TuneOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Connection.TuneOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Connection.Open default encoding/decoding roundtrip")
    func amqpConnectionOpenCoding() async throws {
        let object = Spec.Connection.Open()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Connection.Open.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Connection.OpenOk default encoding/decoding roundtrip")
    func amqpConnectionOpenOkCoding() async throws {
        let object = Spec.Connection.OpenOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Connection.OpenOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Connection.Close default encoding/decoding roundtrip")
    func amqpConnectionCloseCoding() async throws {
        let object = Spec.Connection.Close(replyCode: 1, classId: 1, methodId: 1)
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Connection.Close.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Connection.CloseOk default encoding/decoding roundtrip")
    func amqpConnectionCloseOkCoding() async throws {
        let object = Spec.Connection.CloseOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Connection.CloseOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Connection.Blocked default encoding/decoding roundtrip")
    func amqpConnectionBlockedCoding() async throws {
        let object = Spec.Connection.Blocked()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Connection.Blocked.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Connection.Unblocked default encoding/decoding roundtrip")
    func amqpConnectionUnblockedCoding() async throws {
        let object = Spec.Connection.Unblocked()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Connection.Unblocked.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Connection.UpdateSecret default encoding/decoding roundtrip")
    func amqpConnectionUpdateSecretCoding() async throws {
        let object = Spec.Connection.UpdateSecret(newSecret: "FooBar", reason: "FooBar")
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Connection.UpdateSecret.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Connection.UpdateSecretOk default encoding/decoding roundtrip")
    func amqpConnectionUpdateSecretOkCoding() async throws {
        let object = Spec.Connection.UpdateSecretOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Connection.UpdateSecretOk.self, from: binary)
        #expect(decoded == object)
    }

}

@Suite struct ChannelCoding {
    @Test("Spec.Channel.Open default encoding/decoding roundtrip")
    func amqpChannelOpenCoding() async throws {
        let object = Spec.Channel.Open()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Channel.Open.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Channel.OpenOk default encoding/decoding roundtrip")
    func amqpChannelOpenOkCoding() async throws {
        let object = Spec.Channel.OpenOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Channel.OpenOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Channel.Flow default encoding/decoding roundtrip")
    func amqpChannelFlowCoding() async throws {
        let object = Spec.Channel.Flow(active: true)
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Channel.Flow.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Channel.FlowOk default encoding/decoding roundtrip")
    func amqpChannelFlowOkCoding() async throws {
        let object = Spec.Channel.FlowOk(active: true)
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Channel.FlowOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Channel.Close default encoding/decoding roundtrip")
    func amqpChannelCloseCoding() async throws {
        let object = Spec.Channel.Close(replyCode: 1, classId: 1, methodId: 1)
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Channel.Close.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Channel.CloseOk default encoding/decoding roundtrip")
    func amqpChannelCloseOkCoding() async throws {
        let object = Spec.Channel.CloseOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Channel.CloseOk.self, from: binary)
        #expect(decoded == object)
    }

}

@Suite struct AccessCoding {
    @Test("Spec.Access.Request default encoding/decoding roundtrip")
    func amqpAccessRequestCoding() async throws {
        let object = Spec.Access.Request()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Access.Request.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Access.RequestOk default encoding/decoding roundtrip")
    func amqpAccessRequestOkCoding() async throws {
        let object = Spec.Access.RequestOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Access.RequestOk.self, from: binary)
        #expect(decoded == object)
    }

}

@Suite struct ExchangeCoding {
    @Test("Spec.Exchange.Declare default encoding/decoding roundtrip")
    func amqpExchangeDeclareCoding() async throws {
        let object = Spec.Exchange.Declare(exchange: "FooBar")
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Exchange.Declare.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Exchange.DeclareOk default encoding/decoding roundtrip")
    func amqpExchangeDeclareOkCoding() async throws {
        let object = Spec.Exchange.DeclareOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Exchange.DeclareOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Exchange.Delete default encoding/decoding roundtrip")
    func amqpExchangeDeleteCoding() async throws {
        let object = Spec.Exchange.Delete(exchange: "FooBar")
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Exchange.Delete.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Exchange.DeleteOk default encoding/decoding roundtrip")
    func amqpExchangeDeleteOkCoding() async throws {
        let object = Spec.Exchange.DeleteOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Exchange.DeleteOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Exchange.Bind default encoding/decoding roundtrip")
    func amqpExchangeBindCoding() async throws {
        let object = Spec.Exchange.Bind(destination: "FooBar", source: "FooBar")
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Exchange.Bind.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Exchange.BindOk default encoding/decoding roundtrip")
    func amqpExchangeBindOkCoding() async throws {
        let object = Spec.Exchange.BindOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Exchange.BindOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Exchange.Unbind default encoding/decoding roundtrip")
    func amqpExchangeUnbindCoding() async throws {
        let object = Spec.Exchange.Unbind(destination: "FooBar", source: "FooBar")
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Exchange.Unbind.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Exchange.UnbindOk default encoding/decoding roundtrip")
    func amqpExchangeUnbindOkCoding() async throws {
        let object = Spec.Exchange.UnbindOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Exchange.UnbindOk.self, from: binary)
        #expect(decoded == object)
    }

}

@Suite struct QueueCoding {
    @Test("Spec.Queue.Declare default encoding/decoding roundtrip")
    func amqpQueueDeclareCoding() async throws {
        let object = Spec.Queue.Declare()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Queue.Declare.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Queue.DeclareOk default encoding/decoding roundtrip")
    func amqpQueueDeclareOkCoding() async throws {
        let object = Spec.Queue.DeclareOk(queue: "FooBar", messageCount: 1, consumerCount: 1)
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Queue.DeclareOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Queue.Bind default encoding/decoding roundtrip")
    func amqpQueueBindCoding() async throws {
        let object = Spec.Queue.Bind(exchange: "FooBar")
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Queue.Bind.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Queue.BindOk default encoding/decoding roundtrip")
    func amqpQueueBindOkCoding() async throws {
        let object = Spec.Queue.BindOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Queue.BindOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Queue.Purge default encoding/decoding roundtrip")
    func amqpQueuePurgeCoding() async throws {
        let object = Spec.Queue.Purge()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Queue.Purge.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Queue.PurgeOk default encoding/decoding roundtrip")
    func amqpQueuePurgeOkCoding() async throws {
        let object = Spec.Queue.PurgeOk(messageCount: 1)
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Queue.PurgeOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Queue.Delete default encoding/decoding roundtrip")
    func amqpQueueDeleteCoding() async throws {
        let object = Spec.Queue.Delete()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Queue.Delete.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Queue.DeleteOk default encoding/decoding roundtrip")
    func amqpQueueDeleteOkCoding() async throws {
        let object = Spec.Queue.DeleteOk(messageCount: 1)
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Queue.DeleteOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Queue.Unbind default encoding/decoding roundtrip")
    func amqpQueueUnbindCoding() async throws {
        let object = Spec.Queue.Unbind(exchange: "FooBar")
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Queue.Unbind.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Queue.UnbindOk default encoding/decoding roundtrip")
    func amqpQueueUnbindOkCoding() async throws {
        let object = Spec.Queue.UnbindOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Queue.UnbindOk.self, from: binary)
        #expect(decoded == object)
    }

}

@Suite struct TxCoding {
    @Test("Spec.Tx.Select default encoding/decoding roundtrip")
    func amqpTxSelectCoding() async throws {
        let object = Spec.Tx.Select()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Tx.Select.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Tx.SelectOk default encoding/decoding roundtrip")
    func amqpTxSelectOkCoding() async throws {
        let object = Spec.Tx.SelectOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Tx.SelectOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Tx.Commit default encoding/decoding roundtrip")
    func amqpTxCommitCoding() async throws {
        let object = Spec.Tx.Commit()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Tx.Commit.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Tx.CommitOk default encoding/decoding roundtrip")
    func amqpTxCommitOkCoding() async throws {
        let object = Spec.Tx.CommitOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Tx.CommitOk.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Tx.Rollback default encoding/decoding roundtrip")
    func amqpTxRollbackCoding() async throws {
        let object = Spec.Tx.Rollback()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Tx.Rollback.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Tx.RollbackOk default encoding/decoding roundtrip")
    func amqpTxRollbackOkCoding() async throws {
        let object = Spec.Tx.RollbackOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Tx.RollbackOk.self, from: binary)
        #expect(decoded == object)
    }

}

@Suite struct ConfirmCoding {
    @Test("Spec.Confirm.Select default encoding/decoding roundtrip")
    func amqpConfirmSelectCoding() async throws {
        let object = Spec.Confirm.Select()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Confirm.Select.self, from: binary)
        #expect(decoded == object)
    }

    @Test("Spec.Confirm.SelectOk default encoding/decoding roundtrip")
    func amqpConfirmSelectOkCoding() async throws {
        let object = Spec.Confirm.SelectOk()
        let binary = try FrameEncoder().encode(object)
        #expect(binary.count == object.bytesCount)
        let decoded = try FrameDecoder().decode(Spec.Confirm.SelectOk.self, from: binary)
        #expect(decoded == object)
    }

}
