//   NOTE: This -*- swift -*- source code is autogenerated from the AMQP
//         specification!
//
// TODO: license here
//

import Foundation

extension AMQP.Basic.Qos : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(prefetchSize)
        try encoder.encode(prefetchCount)
        try encoder.encode(global)
    }
}

extension AMQP.Basic.QosOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Basic.Consume : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(ticket)
        try encoder.encode(queue, isLong: false)
        try encoder.encode(consumerTag, isLong: false)
        try encoder.encode(noLocal)
        try encoder.encode(noAck)
        try encoder.encode(exclusive)
        try encoder.encode(nowait)
        try encoder.encode(arguments)
    }
}

extension AMQP.Basic.ConsumeOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(consumerTag, isLong: false)
    }
}

extension AMQP.Basic.Cancel : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(consumerTag, isLong: false)
        try encoder.encode(nowait)
    }
}

extension AMQP.Basic.CancelOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(consumerTag, isLong: false)
    }
}

extension AMQP.Basic.Publish : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(ticket)
        try encoder.encode(exchange, isLong: false)
        try encoder.encode(routingKey, isLong: false)
        try encoder.encode(mandatory)
        try encoder.encode(immediate)
    }
}

extension AMQP.Basic.Return : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(replyCode)
        try encoder.encode(replyText, isLong: false)
        try encoder.encode(exchange, isLong: false)
        try encoder.encode(routingKey, isLong: false)
    }
}

extension AMQP.Basic.Deliver : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(consumerTag, isLong: false)
        try encoder.encode(deliveryTag)
        try encoder.encode(redelivered)
        try encoder.encode(exchange, isLong: false)
        try encoder.encode(routingKey, isLong: false)
    }
}

extension AMQP.Basic.Get : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(ticket)
        try encoder.encode(queue, isLong: false)
        try encoder.encode(noAck)
    }
}

extension AMQP.Basic.GetOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(deliveryTag)
        try encoder.encode(redelivered)
        try encoder.encode(exchange, isLong: false)
        try encoder.encode(routingKey, isLong: false)
        try encoder.encode(messageCount)
    }
}

extension AMQP.Basic.GetEmpty : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(clusterId, isLong: false)
    }
}

extension AMQP.Basic.Ack : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(deliveryTag)
        try encoder.encode(multiple)
    }
}

extension AMQP.Basic.Reject : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(deliveryTag)
        try encoder.encode(requeue)
    }
}

extension AMQP.Basic.RecoverAsync : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(requeue)
    }
}

extension AMQP.Basic.Recover : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(requeue)
    }
}

extension AMQP.Basic.RecoverOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Basic.Nack : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(deliveryTag)
        try encoder.encode(multiple)
        try encoder.encode(requeue)
    }
}

extension AMQP.Connection.Start : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(versionMajor)
        try encoder.encode(versionMinor)
        try encoder.encode(serverProperties)
        try encoder.encode(mechanisms, isLong: true)
        try encoder.encode(locales, isLong: true)
    }
}

extension AMQP.Connection.StartOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(clientProperties)
        try encoder.encode(mechanism, isLong: false)
        try encoder.encode(response, isLong: true)
        try encoder.encode(locale, isLong: false)
    }
}

extension AMQP.Connection.Secure : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(challenge, isLong: true)
    }
}

extension AMQP.Connection.SecureOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(response, isLong: true)
    }
}

extension AMQP.Connection.Tune : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(channelMax)
        try encoder.encode(frameMax)
        try encoder.encode(heartbeat)
    }
}

extension AMQP.Connection.TuneOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(channelMax)
        try encoder.encode(frameMax)
        try encoder.encode(heartbeat)
    }
}

extension AMQP.Connection.Open : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(virtualHost, isLong: false)
        try encoder.encode(capabilities, isLong: false)
        try encoder.encode(insist)
    }
}

extension AMQP.Connection.OpenOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(knownHosts, isLong: false)
    }
}

extension AMQP.Connection.Close : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(replyCode)
        try encoder.encode(replyText, isLong: false)
        try encoder.encode(classId)
        try encoder.encode(methodId)
    }
}

extension AMQP.Connection.CloseOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Connection.Blocked : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(reason, isLong: false)
    }
}

extension AMQP.Connection.Unblocked : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Connection.UpdateSecret : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(newSecret, isLong: true)
        try encoder.encode(reason, isLong: false)
    }
}

extension AMQP.Connection.UpdateSecretOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Channel.Open : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(outOfBand, isLong: false)
    }
}

extension AMQP.Channel.OpenOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(channelId, isLong: true)
    }
}

extension AMQP.Channel.Flow : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(active)
    }
}

extension AMQP.Channel.FlowOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(active)
    }
}

extension AMQP.Channel.Close : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(replyCode)
        try encoder.encode(replyText, isLong: false)
        try encoder.encode(classId)
        try encoder.encode(methodId)
    }
}

extension AMQP.Channel.CloseOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Access.Request : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(realm, isLong: false)
        try encoder.encode(exclusive)
        try encoder.encode(passive)
        try encoder.encode(active)
        try encoder.encode(write)
        try encoder.encode(read)
    }
}

extension AMQP.Access.RequestOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(ticket)
    }
}

extension AMQP.Exchange.Declare : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(ticket)
        try encoder.encode(exchange, isLong: false)
        try encoder.encode(type, isLong: false)
        try encoder.encode(passive)
        try encoder.encode(durable)
        try encoder.encode(autoDelete)
        try encoder.encode(`internal`)
        try encoder.encode(nowait)
        try encoder.encode(arguments)
    }
}

extension AMQP.Exchange.DeclareOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Exchange.Delete : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(ticket)
        try encoder.encode(exchange, isLong: false)
        try encoder.encode(ifUnused)
        try encoder.encode(nowait)
    }
}

extension AMQP.Exchange.DeleteOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Exchange.Bind : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(ticket)
        try encoder.encode(destination, isLong: false)
        try encoder.encode(source, isLong: false)
        try encoder.encode(routingKey, isLong: false)
        try encoder.encode(nowait)
        try encoder.encode(arguments)
    }
}

extension AMQP.Exchange.BindOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Exchange.Unbind : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(ticket)
        try encoder.encode(destination, isLong: false)
        try encoder.encode(source, isLong: false)
        try encoder.encode(routingKey, isLong: false)
        try encoder.encode(nowait)
        try encoder.encode(arguments)
    }
}

extension AMQP.Exchange.UnbindOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Queue.Declare : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(ticket)
        try encoder.encode(queue, isLong: false)
        try encoder.encode(passive)
        try encoder.encode(durable)
        try encoder.encode(exclusive)
        try encoder.encode(autoDelete)
        try encoder.encode(nowait)
        try encoder.encode(arguments)
    }
}

extension AMQP.Queue.DeclareOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(queue, isLong: false)
        try encoder.encode(messageCount)
        try encoder.encode(consumerCount)
    }
}

extension AMQP.Queue.Bind : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(ticket)
        try encoder.encode(queue, isLong: false)
        try encoder.encode(exchange, isLong: false)
        try encoder.encode(routingKey, isLong: false)
        try encoder.encode(nowait)
        try encoder.encode(arguments)
    }
}

extension AMQP.Queue.BindOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Queue.Purge : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(ticket)
        try encoder.encode(queue, isLong: false)
        try encoder.encode(nowait)
    }
}

extension AMQP.Queue.PurgeOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(messageCount)
    }
}

extension AMQP.Queue.Delete : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(ticket)
        try encoder.encode(queue, isLong: false)
        try encoder.encode(ifUnused)
        try encoder.encode(ifEmpty)
        try encoder.encode(nowait)
    }
}

extension AMQP.Queue.DeleteOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(messageCount)
    }
}

extension AMQP.Queue.Unbind : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(ticket)
        try encoder.encode(queue, isLong: false)
        try encoder.encode(exchange, isLong: false)
        try encoder.encode(routingKey, isLong: false)
        try encoder.encode(arguments)
    }
}

extension AMQP.Queue.UnbindOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Tx.Select : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Tx.SelectOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Tx.Commit : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Tx.CommitOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Tx.Rollback : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Tx.RollbackOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}

extension AMQP.Confirm.Select : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
        try encoder.encode(nowait)
    }
}

extension AMQP.Confirm.SelectOk : AMQPEncodable {
    func encode(to encoder: AMQPEncoder) throws {
        try encoder.encode(amqpClassId)
        try encoder.encode(amqpMethodId)
    }
}
