//   NOTE: This -*- swift -*- source code is autogenerated from the AMQP
//         specification!
//
// This source file is part of the swift-amqp open source project
//
// Copyright (c) 2024-2025 swift-amqp project authors
// Licensed under Apache License 2.0
//
// See LICENSE for license information
//
// SPDX-License-Identifier: Apache-2.0
//

protocol AMQPObjectProtocol: Equatable, Sendable {
    var amqpName: String { get }
}

protocol AMQPClassProtocol: AMQPObjectProtocol {
    var amqpClassId: UInt16 { get }
}

protocol AMQPPropertiesProtocol: AMQPObjectProtocol, Hashable {}

protocol AMQPMethodProtocol: AMQPClassProtocol {
    var amqpMethodId: UInt16 { get }
}

// swiftlint:disable nesting type_body_length
public enum Spec {
    public typealias Table = [String: FieldValue]

    public enum FieldValue: Equatable, Hashable, CaseIterable, Sendable {
        public static let allCases: [Self] = [
            .bool(Bool.init()),
            .int8(Int8.init()),
            .uint8(UInt8.init()),
            .int16(Int16.init()),
            .uint16(UInt16.init()),
            .int32(Int32.init()),
            .uint32(UInt32.init()),
            .int64(Int64.init()),
            .f32(Float.init()),
            .f64(Double.init()),
            .decimal(0, 0),
            .longstr(String.init()),
            .array([FieldValue].init()),
            .timestamp(Timestamp.distantPast),
            .table([:]),
            .bytes([UInt8].init()),
            .void,
        ]

        case bool(Bool)
        case int8(Int8)
        case uint8(UInt8)
        case int16(Int16)
        case uint16(UInt16)
        case int32(Int32)
        case uint32(UInt32)
        case int64(Int64)
        case f32(Float)
        case f64(Double)
        case decimal(UInt8, Int32)
        case longstr(String)
        case array([FieldValue])
        case timestamp(Timestamp)
        case table(Table)
        case bytes([UInt8])
        case void

        var type: UInt8 {
            switch self {
            case .bool: return Character("t").asciiValue!
            case .int8: return Character("b").asciiValue!
            case .uint8: return Character("B").asciiValue!
            case .int16: return Character("s").asciiValue!
            case .uint16: return Character("u").asciiValue!
            case .int32: return Character("I").asciiValue!
            case .uint32: return Character("i").asciiValue!
            case .int64: return Character("l").asciiValue!
            case .f32: return Character("f").asciiValue!
            case .f64: return Character("d").asciiValue!
            case .decimal: return Character("D").asciiValue!
            case .longstr: return Character("S").asciiValue!
            case .array: return Character("A").asciiValue!
            case .timestamp: return Character("T").asciiValue!
            case .table: return Character("F").asciiValue!
            case .bytes: return Character("x").asciiValue!
            case .void: return Character("V").asciiValue!
            }
        }

        var bytesCount: UInt32 {
            // 1 extra byte to store the type info
            switch self {
            case .bool: return 1 + 1
            case .int8: return 1 + 1
            case .uint8: return 1 + 1
            case .int16: return 2 + 1
            case .uint16: return 2 + 1
            case .int32: return 4 + 1
            case .uint32: return 4 + 1
            case .int64: return 8 + 1
            case .f32: return 4 + 1
            case .f64: return 8 + 1
            case .decimal: return 5 + 1
            case .longstr(let value): return value.longBytesCount + 1
            case .array(let value): return value.reduce(into: 0) { $0 += $1.bytesCount } + 1 + 4
            case .timestamp: return 8 + 1
            case .table(let value): return value.bytesCount + 1
            case .bytes(let value): return UInt32(value.count) + 1 + 4
            case .void: return 1 + 1
            }
        }
    }

    public struct ProtocolLevel {
        static let major: UInt8 = 0
        static let minor: UInt8 = 9
        static let revision: UInt8 = 1
        static let port = 5672
    }

    static let frameMethod: UInt8 = 1
    static let frameHeader: UInt8 = 2
    static let frameBody: UInt8 = 3
    static let frameHeartbeat: UInt8 = 8
    static let frameMinSize = 4096
    static let frameEnd: UInt8 = 206
    static let replySuccess = 200

    enum SoftError: Int, Error {
        case contentTooLarge = 311
        case noRoute = 312
        case noConsumers = 313
        case accessRefused = 403
        case notFound = 404
        case resourceLocked = 405
        case preconditionFailed = 406
    }

    enum HardError: Int, Error {
        case connectionForced = 320
        case invalidPath = 402
        case frameError = 501
        case syntaxError = 502
        case commandInvalid = 503
        case channelError = 504
        case unexpectedFrame = 505
        case resourceError = 506
        case notAllowed = 530
        case notImplemented = 540
        case internalError = 541
    }

    public struct Basic: AMQPClassProtocol {
        public var amqpClassId: UInt16 { 60 }
        public var amqpName: String { "basic" }

        public struct Qos: AMQPMethodProtocol {
            public private(set) var prefetchSize: Int32 = 0
            public private(set) var prefetchCount: UInt16 = 0
            public private(set) var global: Bool = false

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 10 }
            public var amqpName: String { "basic.qos" }
        }

        public struct QosOk: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 11 }
            public var amqpName: String { "basic.qos-ok" }
        }

        public struct Consume: AMQPMethodProtocol {
            public private(set) var ticket: UInt16 = 0
            public private(set) var queue: String = ""
            public private(set) var consumerTag: String = ""
            public private(set) var noLocal: Bool = false
            public private(set) var noAck: Bool = false
            public private(set) var exclusive: Bool = false
            public private(set) var nowait: Bool = false
            public private(set) var arguments: [String: FieldValue] = [:]

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 20 }
            public var amqpName: String { "basic.consume" }
        }

        public struct ConsumeOk: AMQPMethodProtocol {
            public private(set) var consumerTag: String

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 21 }
            public var amqpName: String { "basic.consume-ok" }
        }

        public struct Cancel: AMQPMethodProtocol {
            public private(set) var consumerTag: String
            public private(set) var nowait: Bool = false

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 30 }
            public var amqpName: String { "basic.cancel" }
        }

        public struct CancelOk: AMQPMethodProtocol {
            public private(set) var consumerTag: String

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 31 }
            public var amqpName: String { "basic.cancel-ok" }
        }

        public struct Publish: AMQPMethodProtocol {
            public private(set) var ticket: UInt16 = 0
            public private(set) var exchange: String = ""
            public private(set) var routingKey: String = ""
            public private(set) var mandatory: Bool = false
            public private(set) var immediate: Bool = false

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 40 }
            public var amqpName: String { "basic.publish" }
        }

        public struct Return: AMQPMethodProtocol {
            public private(set) var replyCode: UInt16
            public private(set) var replyText: String = ""
            public private(set) var exchange: String
            public private(set) var routingKey: String

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 50 }
            public var amqpName: String { "basic.return" }
        }

        public struct Deliver: AMQPMethodProtocol {
            public private(set) var consumerTag: String
            public private(set) var deliveryTag: Int64
            public private(set) var redelivered: Bool = false
            public private(set) var exchange: String
            public private(set) var routingKey: String

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 60 }
            public var amqpName: String { "basic.deliver" }
        }

        public struct Get: AMQPMethodProtocol {
            public private(set) var ticket: UInt16 = 0
            public private(set) var queue: String = ""
            public private(set) var noAck: Bool = false

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 70 }
            public var amqpName: String { "basic.get" }
        }

        public struct GetOk: AMQPMethodProtocol {
            public private(set) var deliveryTag: Int64
            public private(set) var redelivered: Bool = false
            public private(set) var exchange: String
            public private(set) var routingKey: String
            public private(set) var messageCount: Int32

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 71 }
            public var amqpName: String { "basic.get-ok" }
        }

        public struct GetEmpty: AMQPMethodProtocol {
            public private(set) var clusterId: String = ""

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 72 }
            public var amqpName: String { "basic.get-empty" }
        }

        public struct Ack: AMQPMethodProtocol {
            public private(set) var deliveryTag: Int64 = 0
            public private(set) var multiple: Bool = false

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 80 }
            public var amqpName: String { "basic.ack" }
        }

        public struct Reject: AMQPMethodProtocol {
            public private(set) var deliveryTag: Int64
            public private(set) var requeue: Bool = true

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 90 }
            public var amqpName: String { "basic.reject" }
        }

        public struct RecoverAsync: AMQPMethodProtocol {
            public private(set) var requeue: Bool = false

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 100 }
            public var amqpName: String { "basic.recover-async" }
        }

        public struct Recover: AMQPMethodProtocol {
            public private(set) var requeue: Bool = false

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 110 }
            public var amqpName: String { "basic.recover" }
        }

        public struct RecoverOk: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 111 }
            public var amqpName: String { "basic.recover-ok" }
        }

        public struct Nack: AMQPMethodProtocol {
            public private(set) var deliveryTag: Int64 = 0
            public private(set) var multiple: Bool = false
            public private(set) var requeue: Bool = true

            public var amqpClassId: UInt16 { 60 }
            public var amqpMethodId: UInt16 { 120 }
            public var amqpName: String { "basic.nack" }
        }
    }

    public struct Connection: AMQPClassProtocol {
        public var amqpClassId: UInt16 { 10 }
        public var amqpName: String { "connection" }

        public struct Start: AMQPMethodProtocol {
            public private(set) var versionMajor: Int8 = 0
            public private(set) var versionMinor: Int8 = 9
            public private(set) var serverProperties: [String: FieldValue]
            public private(set) var mechanisms: String = "PLAIN"
            public private(set) var locales: String = "en_US"

            public var amqpClassId: UInt16 { 10 }
            public var amqpMethodId: UInt16 { 10 }
            public var amqpName: String { "connection.start" }
        }

        public struct StartOk: AMQPMethodProtocol {
            public private(set) var clientProperties: [String: FieldValue]
            public private(set) var mechanism: String = "PLAIN"
            public private(set) var response: String
            public private(set) var locale: String = "en_US"

            public var amqpClassId: UInt16 { 10 }
            public var amqpMethodId: UInt16 { 11 }
            public var amqpName: String { "connection.start-ok" }
        }

        public struct Secure: AMQPMethodProtocol {
            public private(set) var challenge: String

            public var amqpClassId: UInt16 { 10 }
            public var amqpMethodId: UInt16 { 20 }
            public var amqpName: String { "connection.secure" }
        }

        public struct SecureOk: AMQPMethodProtocol {
            public private(set) var response: String

            public var amqpClassId: UInt16 { 10 }
            public var amqpMethodId: UInt16 { 21 }
            public var amqpName: String { "connection.secure-ok" }
        }

        public struct Tune: AMQPMethodProtocol {
            public private(set) var channelMax: UInt16 = 0
            public private(set) var frameMax: Int32 = 0
            public private(set) var heartbeat: UInt16 = 0

            public var amqpClassId: UInt16 { 10 }
            public var amqpMethodId: UInt16 { 30 }
            public var amqpName: String { "connection.tune" }
        }

        public struct TuneOk: AMQPMethodProtocol {
            public private(set) var channelMax: UInt16 = 0
            public private(set) var frameMax: Int32 = 0
            public private(set) var heartbeat: UInt16 = 0

            public var amqpClassId: UInt16 { 10 }
            public var amqpMethodId: UInt16 { 31 }
            public var amqpName: String { "connection.tune-ok" }
        }

        public struct Open: AMQPMethodProtocol {
            public private(set) var virtualHost: String = "/"
            public private(set) var capabilities: String = ""
            public private(set) var insist: Bool = false

            public var amqpClassId: UInt16 { 10 }
            public var amqpMethodId: UInt16 { 40 }
            public var amqpName: String { "connection.open" }
        }

        public struct OpenOk: AMQPMethodProtocol {
            public private(set) var knownHosts: String = ""

            public var amqpClassId: UInt16 { 10 }
            public var amqpMethodId: UInt16 { 41 }
            public var amqpName: String { "connection.open-ok" }
        }

        public struct Close: AMQPMethodProtocol {
            public private(set) var replyCode: UInt16
            public private(set) var replyText: String = ""
            public private(set) var classId: UInt16
            public private(set) var methodId: UInt16

            public var amqpClassId: UInt16 { 10 }
            public var amqpMethodId: UInt16 { 50 }
            public var amqpName: String { "connection.close" }
        }

        public struct CloseOk: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 10 }
            public var amqpMethodId: UInt16 { 51 }
            public var amqpName: String { "connection.close-ok" }
        }

        public struct Blocked: AMQPMethodProtocol {
            public private(set) var reason: String = ""

            public var amqpClassId: UInt16 { 10 }
            public var amqpMethodId: UInt16 { 60 }
            public var amqpName: String { "connection.blocked" }
        }

        public struct Unblocked: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 10 }
            public var amqpMethodId: UInt16 { 61 }
            public var amqpName: String { "connection.unblocked" }
        }

        public struct UpdateSecret: AMQPMethodProtocol {
            public private(set) var newSecret: String
            public private(set) var reason: String

            public var amqpClassId: UInt16 { 10 }
            public var amqpMethodId: UInt16 { 70 }
            public var amqpName: String { "connection.update-secret" }
        }

        public struct UpdateSecretOk: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 10 }
            public var amqpMethodId: UInt16 { 71 }
            public var amqpName: String { "connection.update-secret-ok" }
        }
    }

    public struct Channel: AMQPClassProtocol {
        public var amqpClassId: UInt16 { 20 }
        public var amqpName: String { "channel" }

        public struct Open: AMQPMethodProtocol {
            public private(set) var outOfBand: String = ""

            public var amqpClassId: UInt16 { 20 }
            public var amqpMethodId: UInt16 { 10 }
            public var amqpName: String { "channel.open" }
        }

        public struct OpenOk: AMQPMethodProtocol {
            public private(set) var channelId: String = ""

            public var amqpClassId: UInt16 { 20 }
            public var amqpMethodId: UInt16 { 11 }
            public var amqpName: String { "channel.open-ok" }
        }

        public struct Flow: AMQPMethodProtocol {
            public private(set) var active: Bool

            public var amqpClassId: UInt16 { 20 }
            public var amqpMethodId: UInt16 { 20 }
            public var amqpName: String { "channel.flow" }
        }

        public struct FlowOk: AMQPMethodProtocol {
            public private(set) var active: Bool

            public var amqpClassId: UInt16 { 20 }
            public var amqpMethodId: UInt16 { 21 }
            public var amqpName: String { "channel.flow-ok" }
        }

        public struct Close: AMQPMethodProtocol {
            public private(set) var replyCode: UInt16
            public private(set) var replyText: String = ""
            public private(set) var classId: UInt16
            public private(set) var methodId: UInt16

            public var amqpClassId: UInt16 { 20 }
            public var amqpMethodId: UInt16 { 40 }
            public var amqpName: String { "channel.close" }
        }

        public struct CloseOk: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 20 }
            public var amqpMethodId: UInt16 { 41 }
            public var amqpName: String { "channel.close-ok" }
        }
    }

    public struct Access: AMQPClassProtocol {
        public var amqpClassId: UInt16 { 30 }
        public var amqpName: String { "access" }

        public struct Request: AMQPMethodProtocol {
            public private(set) var realm: String = "/data"
            public private(set) var exclusive: Bool = false
            public private(set) var passive: Bool = true
            public private(set) var active: Bool = true
            public private(set) var write: Bool = true
            public private(set) var read: Bool = true

            public var amqpClassId: UInt16 { 30 }
            public var amqpMethodId: UInt16 { 10 }
            public var amqpName: String { "access.request" }
        }

        public struct RequestOk: AMQPMethodProtocol {
            public private(set) var ticket: UInt16 = 1

            public var amqpClassId: UInt16 { 30 }
            public var amqpMethodId: UInt16 { 11 }
            public var amqpName: String { "access.request-ok" }
        }
    }

    public struct Exchange: AMQPClassProtocol {
        public var amqpClassId: UInt16 { 40 }
        public var amqpName: String { "exchange" }

        public struct Declare: AMQPMethodProtocol {
            public private(set) var ticket: UInt16 = 0
            public private(set) var exchange: String
            public private(set) var type: String = "direct"
            public private(set) var passive: Bool = false
            public private(set) var durable: Bool = false
            public private(set) var autoDelete: Bool = false
            public private(set) var `internal`: Bool = false
            public private(set) var nowait: Bool = false
            public private(set) var arguments: [String: FieldValue] = [:]

            public var amqpClassId: UInt16 { 40 }
            public var amqpMethodId: UInt16 { 10 }
            public var amqpName: String { "exchange.declare" }
        }

        public struct DeclareOk: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 40 }
            public var amqpMethodId: UInt16 { 11 }
            public var amqpName: String { "exchange.declare-ok" }
        }

        public struct Delete: AMQPMethodProtocol {
            public private(set) var ticket: UInt16 = 0
            public private(set) var exchange: String
            public private(set) var ifUnused: Bool = false
            public private(set) var nowait: Bool = false

            public var amqpClassId: UInt16 { 40 }
            public var amqpMethodId: UInt16 { 20 }
            public var amqpName: String { "exchange.delete" }
        }

        public struct DeleteOk: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 40 }
            public var amqpMethodId: UInt16 { 21 }
            public var amqpName: String { "exchange.delete-ok" }
        }

        public struct Bind: AMQPMethodProtocol {
            public private(set) var ticket: UInt16 = 0
            public private(set) var destination: String
            public private(set) var source: String
            public private(set) var routingKey: String = ""
            public private(set) var nowait: Bool = false
            public private(set) var arguments: [String: FieldValue] = [:]

            public var amqpClassId: UInt16 { 40 }
            public var amqpMethodId: UInt16 { 30 }
            public var amqpName: String { "exchange.bind" }
        }

        public struct BindOk: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 40 }
            public var amqpMethodId: UInt16 { 31 }
            public var amqpName: String { "exchange.bind-ok" }
        }

        public struct Unbind: AMQPMethodProtocol {
            public private(set) var ticket: UInt16 = 0
            public private(set) var destination: String
            public private(set) var source: String
            public private(set) var routingKey: String = ""
            public private(set) var nowait: Bool = false
            public private(set) var arguments: [String: FieldValue] = [:]

            public var amqpClassId: UInt16 { 40 }
            public var amqpMethodId: UInt16 { 40 }
            public var amqpName: String { "exchange.unbind" }
        }

        public struct UnbindOk: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 40 }
            public var amqpMethodId: UInt16 { 51 }
            public var amqpName: String { "exchange.unbind-ok" }
        }
    }

    public struct Queue: AMQPClassProtocol {
        public var amqpClassId: UInt16 { 50 }
        public var amqpName: String { "queue" }

        public struct Declare: AMQPMethodProtocol {
            public private(set) var ticket: UInt16 = 0
            public private(set) var queue: String = ""
            public private(set) var passive: Bool = false
            public private(set) var durable: Bool = false
            public private(set) var exclusive: Bool = false
            public private(set) var autoDelete: Bool = false
            public private(set) var nowait: Bool = false
            public private(set) var arguments: [String: FieldValue] = [:]

            public var amqpClassId: UInt16 { 50 }
            public var amqpMethodId: UInt16 { 10 }
            public var amqpName: String { "queue.declare" }
        }

        public struct DeclareOk: AMQPMethodProtocol {
            public private(set) var queue: String
            public private(set) var messageCount: Int32
            public private(set) var consumerCount: Int32

            public var amqpClassId: UInt16 { 50 }
            public var amqpMethodId: UInt16 { 11 }
            public var amqpName: String { "queue.declare-ok" }
        }

        public struct Bind: AMQPMethodProtocol {
            public private(set) var ticket: UInt16 = 0
            public private(set) var queue: String = ""
            public private(set) var exchange: String
            public private(set) var routingKey: String = ""
            public private(set) var nowait: Bool = false
            public private(set) var arguments: [String: FieldValue] = [:]

            public var amqpClassId: UInt16 { 50 }
            public var amqpMethodId: UInt16 { 20 }
            public var amqpName: String { "queue.bind" }
        }

        public struct BindOk: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 50 }
            public var amqpMethodId: UInt16 { 21 }
            public var amqpName: String { "queue.bind-ok" }
        }

        public struct Purge: AMQPMethodProtocol {
            public private(set) var ticket: UInt16 = 0
            public private(set) var queue: String = ""
            public private(set) var nowait: Bool = false

            public var amqpClassId: UInt16 { 50 }
            public var amqpMethodId: UInt16 { 30 }
            public var amqpName: String { "queue.purge" }
        }

        public struct PurgeOk: AMQPMethodProtocol {
            public private(set) var messageCount: Int32

            public var amqpClassId: UInt16 { 50 }
            public var amqpMethodId: UInt16 { 31 }
            public var amqpName: String { "queue.purge-ok" }
        }

        public struct Delete: AMQPMethodProtocol {
            public private(set) var ticket: UInt16 = 0
            public private(set) var queue: String = ""
            public private(set) var ifUnused: Bool = false
            public private(set) var ifEmpty: Bool = false
            public private(set) var nowait: Bool = false

            public var amqpClassId: UInt16 { 50 }
            public var amqpMethodId: UInt16 { 40 }
            public var amqpName: String { "queue.delete" }
        }

        public struct DeleteOk: AMQPMethodProtocol {
            public private(set) var messageCount: Int32

            public var amqpClassId: UInt16 { 50 }
            public var amqpMethodId: UInt16 { 41 }
            public var amqpName: String { "queue.delete-ok" }
        }

        public struct Unbind: AMQPMethodProtocol {
            public private(set) var ticket: UInt16 = 0
            public private(set) var queue: String = ""
            public private(set) var exchange: String
            public private(set) var routingKey: String = ""
            public private(set) var arguments: [String: FieldValue] = [:]

            public var amqpClassId: UInt16 { 50 }
            public var amqpMethodId: UInt16 { 50 }
            public var amqpName: String { "queue.unbind" }
        }

        public struct UnbindOk: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 50 }
            public var amqpMethodId: UInt16 { 51 }
            public var amqpName: String { "queue.unbind-ok" }
        }
    }

    public struct Tx: AMQPClassProtocol {
        public var amqpClassId: UInt16 { 90 }
        public var amqpName: String { "tx" }

        public struct Select: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 90 }
            public var amqpMethodId: UInt16 { 10 }
            public var amqpName: String { "tx.select" }
        }

        public struct SelectOk: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 90 }
            public var amqpMethodId: UInt16 { 11 }
            public var amqpName: String { "tx.select-ok" }
        }

        public struct Commit: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 90 }
            public var amqpMethodId: UInt16 { 20 }
            public var amqpName: String { "tx.commit" }
        }

        public struct CommitOk: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 90 }
            public var amqpMethodId: UInt16 { 21 }
            public var amqpName: String { "tx.commit-ok" }
        }

        public struct Rollback: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 90 }
            public var amqpMethodId: UInt16 { 30 }
            public var amqpName: String { "tx.rollback" }
        }

        public struct RollbackOk: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 90 }
            public var amqpMethodId: UInt16 { 31 }
            public var amqpName: String { "tx.rollback-ok" }
        }
    }

    public struct Confirm: AMQPClassProtocol {
        public var amqpClassId: UInt16 { 85 }
        public var amqpName: String { "confirm" }

        public struct Select: AMQPMethodProtocol {
            public private(set) var nowait: Bool = false

            public var amqpClassId: UInt16 { 85 }
            public var amqpMethodId: UInt16 { 10 }
            public var amqpName: String { "confirm.select" }
        }

        public struct SelectOk: AMQPMethodProtocol {

            public var amqpClassId: UInt16 { 85 }
            public var amqpMethodId: UInt16 { 11 }
            public var amqpName: String { "confirm.select-ok" }
        }
    }

    public struct BasicProperties: AMQPPropertiesProtocol {
        public private(set) var contentType: String?
        public private(set) var contentEncoding: String?
        public private(set) var headers: [String: FieldValue]?
        public private(set) var deliveryMode: Int8?
        public private(set) var priority: Int8?
        public private(set) var correlationId: String?
        public private(set) var replyTo: String?
        public private(set) var expiration: String?
        public private(set) var messageId: String?
        public private(set) var timestamp: Timestamp?
        public private(set) var type: String?
        public private(set) var userId: String?
        public private(set) var appId: String?
        public private(set) var clusterId: String?

        public var amqpClassId: UInt16 { 60 }
        public var amqpName: String { "basic" }

        public init(
            contentType: String? = nil,
            contentEncoding: String? = nil,
            headers: [String: FieldValue]? = nil,
            deliveryMode: Int8? = nil,
            priority: Int8? = nil,
            correlationId: String? = nil,
            replyTo: String? = nil,
            expiration: String? = nil,
            messageId: String? = nil,
            timestamp: Timestamp? = nil,
            type: String? = nil,
            userId: String? = nil,
            appId: String? = nil,
            clusterId: String? = nil,
        ) {
            self.contentType = contentType
            self.contentEncoding = contentEncoding
            self.headers = headers
            self.deliveryMode = deliveryMode
            self.priority = priority
            self.correlationId = correlationId
            self.replyTo = replyTo
            self.expiration = expiration
            self.messageId = messageId
            self.timestamp = timestamp
            self.type = type
            self.userId = userId
            self.appId = appId
            self.clusterId = clusterId
        }

    }
}
// swiftlint:enable nesting type_body_length
